           
name: Deploy to Dev Environment

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Install EF Tool
      run: dotnet tool install --global dotnet-ef

    - name: Add .NET tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Run DB Migration (DEV)
      run: dotnet ef database update --connection "${{ secrets.DB_CONNECTION_STRING }}"

    - name: Deploy to Azure Dev Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "appservice-productapi"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish